In [1]:
import random
import numpy as np
# from epnp_2 import * 

In [2]:
x = random.random()
y = random.random()
z = random.random()

print("[",x,", ",y,", ",z,"],")

[ 0.6347295924219996 ,  0.5303702484670442 ,  0.3460914532939693 ],


In [3]:
n = 20
Xw = np.empty((n,3))
for i in range(n):
    Xw[i,:] = np.array([random.random(), random.random(), random.random()])
    print(Xw[i,:])

[0.80015285 0.48342706 0.87542025]
[0.77967985 0.21588826 0.15176404]
[0.5265546  0.23878458 0.21648848]
[0.68931992 0.4267547  0.0784942 ]
[0.97795604 0.38795314 0.78549378]
[0.72877237 0.39986856 0.37676712]
[0.33638135 0.59147967 0.95845994]
[0.47376004 0.90890964 0.25221819]
[0.2725726  0.62844848 0.76636315]
[0.29885736 0.90760139 0.10471023]
[0.77217426 0.03835235 0.20061507]
[0.58581882 0.27284068 0.71146852]
[0.79267015 0.84187683 0.19794622]
[0.88032737 0.22753822 0.77410655]
[0.38669689 0.72398091 0.62954043]
[0.23272866 0.28462935 0.842804  ]
[0.50927637 0.68304945 0.5577211 ]
[0.56483665 0.14423338 0.30388075]
[0.00319476 0.06553819 0.31594862]
[0.44005539 0.27665454 0.42772043]


In [4]:
ph_w = np.array([
    [ 0.995555881938209 ,  0.4802387824086085 ,  0.01206817493434742 , 1.],
    [ 0.48201950525607407 ,  0.03667711951818575 ,  0.2247198631984184 , 1.],
    [ 0.39687422295226926 ,  0.4468422492615619 ,  0.5579296060298905 , 1.],
    [ 0.1307361548312025 ,  0.0017949235578693656 ,  0.7992104944714973 , 1.],
    [ 0.1802038827293625 ,  0.30147195450672637 ,  0.3065432070634452 , 1.],
    [ 0.1273136116768765 ,  0.6008489312233133 ,  0.814072408443261 , 1.],
    [ 0.5936937283176116 ,  0.5617129604604256 ,  0.21464775634992062 , 1.],
    [ 0.07119734746580442 ,  0.777510858755277 ,  0.7501307315179284 , 1.],
    [ 0.32389704460643065 ,  0.8900472338710688 ,  0.15140266567649263 , 1.],
    [ 0.4290695543893176 ,  0.4611765374631873 ,  0.9408351719872696 , 1.]
]).T
n = np.shape(ph_w)[1]
ph_w = ph_w.reshape(4,n)

In [5]:
p_w = np.empty((n,3))
np.shape(p_w)

(10, 3)

In [6]:
print(np.eye(3,4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [7]:
ph_w = np.array([
    [ 0.995555881938209 ,  0.4802387824086085 ,  0.01206817493434742 , 1.],
    [ 0.48201950525607407 ,  0.03667711951818575 ,  0.2247198631984184 , 1.],
    [ 0.39687422295226926 ,  0.4468422492615619 ,  0.5579296060298905 , 1.],
    [ 0.1307361548312025 ,  0.0017949235578693656 ,  0.7992104944714973 , 1.],
    [ 0.1802038827293625 ,  0.30147195450672637 ,  0.3065432070634452 , 1.],
    [ 0.1273136116768765 ,  0.6008489312233133 ,  0.814072408443261 , 1.],
    [ 0.5936937283176116 ,  0.5617129604604256 ,  0.21464775634992062 , 1.],
    [ 0.07119734746580442 ,  0.777510858755277 ,  0.7501307315179284 , 1.],
    [ 0.32389704460643065 ,  0.8900472338710688 ,  0.15140266567649263 , 1.],
    [ 0.4290695543893176 ,  0.4611765374631873 ,  0.9408351719872696 , 1.]
]).T
ph_w[2,0]

0.01206817493434742